image: node:latest

include:
  template: Jobs/Code-Quality.gitlab-ci.yml

cache:
  paths:
    - node_modules/

stages:
  - setup
  - test

install_modules:
  stage: setup
  script:
    - echo "Installing dependencies"
    - yarn

lint:
  stage: test
  dependencies:
    - install_modules
  script:
    - echo "Linting"
    - yarn run lint

test:
  stage: test
  dependencies:
    - install_modules
  script:
    - echo "Running tests"
    - yarn run test
